version: '2'

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:7.7-community
    ports:
      - 9000:9000
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:mysql://sonar_mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    volumes:
      - ./volumes/sonarqube/config:/opt/sonarqube/conf
      - ./volumes/sonarqube/data:/opt/sonarqube/data
      - ./volumes/sonarqube/extensions:/opt/sonarqube/extensions
      - ./volumes/sonarqube/plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - sonar_mysql

  sonar_mysql:
    container_name: sonar_mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sonar
      - MYSQL_USER=sonar
      - MYSQL_PASSWORD=sonar
    volumes:
      - ./volumes/mysql:/var/lib/mysql