version: '2'

services:
  jenkins:
    user: root
    container_name: jenkins
    image: jenkinsci/blueocean
    ports:
      - 9100:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME:/home